name: mrf-paper
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - nose=1.3.7
  - numpy=1.17.2
  - pandas=0.25.1
  - pip=19.2.3
  - python=3.7.4
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - pip:
      - future==0.18.3
      - matplotlib2tikz==0.7.6
      - scienceplots==2.1.0
      - seaborn==0.12.2
